export { default as PostCard } from './PostCard'
export { default as PostWidget } from './PostWidget'
export { default as PostWidgetBottom } from './PostWidgetBottom'
export { default as Categories } from './Categories'
export { default as Header } from './Header'
export { default as Layout } from './Layout'
export { default as Author} from './Author'
export { default as Comments} from './Comments'
export { default as CommentsForm} from './CommentsForm'
export { default as PostDetail} from './PostDetail'
export { default as MainPage } from './MainPage'
export { default as Blog } from './Blog'
export { default as ParallaxImage } from './Parallax'
export { default as About } from './About'
export { default as Services } from './Services'
export { default as Work } from './Work'
export { default as Contact } from './Contact'
export { default as Popup } from './Popup'
export { default as Footer } from './Footer'